/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gustavoz.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import br.com.gustavoz.dao.DaoFornecedor;
import br.com.gustavoz.dao.DaoFuncionario;

public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify tis code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmFornecedor = new javax.swing.JMenuItem();
        jmFuncionario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jRelForn = new javax.swing.JMenuItem();
        jRelFunc = new javax.swing.JMenuItem();
        fechar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Exemplo");
        setMinimumSize(new java.awt.Dimension(300, 300));

        jAreaTrabalho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema de Biblioteca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jmbMenuPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmbMenuPrincipal.setPreferredSize(new java.awt.Dimension(157, 30));

        jmCadastro.setText("Cadastro");

        jmFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        jmFornecedor.setText("Fornecedor");
        jmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFornecedorActionPerformed(evt);
            }
        });
        jmCadastro.add(jmFornecedor);

        jmFuncionario.setText("Funcionario");
        jmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmFuncionario);

        jmbMenuPrincipal.add(jmCadastro);

        jMenu1.setText("Relatórios");

        jRelForn.setText("Fornecedor");
        jRelForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelFornActionPerformed(evt);
            }
        });
        jMenu1.add(jRelForn);

        jRelFunc.setText("Funcionario");
        jRelFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelFuncActionPerformed(evt);
            }
        });
        jMenu1.add(jRelFunc);

        jmbMenuPrincipal.add(jMenu1);

        fechar.setText("Sair");
        fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fecharMouseClicked(evt);
            }
        });
        jmbMenuPrincipal.add(fechar);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadFornecedor(){
        TelaListaFornecedor gcp = new TelaListaFornecedor();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
    private void abrirCadFuncionario(){
        TelaListaFuncionario gcp = new TelaListaFuncionario();
        jAreaTrabalho.add(gcp);
        gcp.setVisible(true);
    }//fecha método
    
   
    
    
    
    private void jmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFornecedorActionPerformed
        TelaListaFornecedor frameTelaListaFornecedor = new TelaListaFornecedor();
        frameTelaListaFornecedor.setVisible(true);
    }//GEN-LAST:event_jmFornecedorActionPerformed

    private void fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecharMouseClicked
       this.fechar();
    }                                      
    private void fechar(){
        if(javax.swing.JOptionPane.showConfirmDialog(null,"Deseja Fechar?","ATENÇÂO ",javax.swing.JOptionPane.YES_NO_OPTION )==0){
            this.dispose();
        }
    }//GEN-LAST:event_fecharMouseClicked

    private void jmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFuncionarioActionPerformed
         TelaListaFuncionario frameTelaListaFuncionario = new TelaListaFuncionario();
        frameTelaListaFuncionario.setVisible(true);
    }//GEN-LAST:event_jmFuncionarioActionPerformed

    private void jRelFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelFuncActionPerformed
        RelatorioFuncionario frameRelatorioFuncionario = new RelatorioFuncionario();
        frameRelatorioFuncionario.setVisible(true);
    }//GEN-LAST:event_jRelFuncActionPerformed

    private void jRelFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelFornActionPerformed
        RelatorioFornecedor frameRelatorioFornecedor = new RelatorioFornecedor();
        frameRelatorioFornecedor.setVisible(true);
    }//GEN-LAST:event_jRelFornActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fechar;
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jRelForn;
    private javax.swing.JMenuItem jRelFunc;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenuItem jmFornecedor;
    private javax.swing.JMenuItem jmFuncionario;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
